# Generated by Django 5.2.7 on 2025-10-28 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentCode', models.CharField(max_length=32)),
                ('FullName', models.CharField(blank=True, default='', max_length=128)),
                ('CourseName', models.CharField(max_length=100)),
                ('Midterm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('Final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('Other', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('WeightMidterm', models.DecimalField(decimal_places=2, default=0.4, max_digits=4)),
                ('WeightFinal', models.DecimalField(decimal_places=2, default=0.6, max_digits=4)),
                ('WeightOther', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Scores',
                'ordering': ['StudentCode', 'CourseName'],
                'indexes': [models.Index(fields=['StudentCode'], name='Scores_Student_d592d6_idx'), models.Index(fields=['CourseName'], name='Scores_CourseN_a06290_idx')],
                'unique_together': {('StudentCode', 'CourseName')},
            },
        ),
    ]
