# Generated by Django 5.2.6 on 2025-10-29 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='score',
            name='Attendance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm chuyên cần'),
        ),
        migrations.AlterField(
            model_name='score',
            name='CourseName',
            field=models.CharField(max_length=128, verbose_name='Tên học phần'),
        ),
        migrations.AlterField(
            model_name='score',
            name='Final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm cuối kỳ'),
        ),
        migrations.AlterField(
            model_name='score',
            name='FullName',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='score',
            name='Midterm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm giữa kỳ'),
        ),
        migrations.AlterField(
            model_name='score',
            name='StudentCode',
            field=models.CharField(max_length=32, verbose_name='Mã sinh viên'),
        ),
        migrations.RemoveField(
            model_name='score',
            name='Other',
        ),
        migrations.RemoveField(
            model_name='score',
            name='WeightFinal',
        ),
        migrations.RemoveField(
            model_name='score',
            name='WeightMidterm',
        ),
        migrations.RemoveField(
            model_name='score',
            name='WeightOther',
        ),
    ]
