# Generated by Django 5.2.6 on 2025-11-06 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('account_id', models.AutoField(db_column='AccountID', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=100)),
                ('role', models.CharField(db_column='Role', max_length=20)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('token_id', models.AutoField(db_column='TokenID', primary_key=True, serialize=False)),
                ('access_token', models.TextField(db_column='AccessToken')),
                ('refresh_token', models.TextField(db_column='RefreshToken')),
                ('access_token_expiry', models.DateTimeField(db_column='AccessTokenExpiry')),
                ('refresh_token_expiry', models.DateTimeField(db_column='RefreshTokenExpiry')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('is_revoked', models.BooleanField(db_column='IsRevoked', default=False)),
                ('account', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tokens',
            },
        ),
    ]
