# Generated by Django 5.2.7 on 2025-10-04 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('token_id', models.AutoField(db_column='TokenID', primary_key=True, serialize=False)),
                ('access_token', models.TextField(db_column='AccessToken')),
                ('refresh_token', models.TextField(db_column='RefreshToken')),
                ('access_token_expiry', models.DateTimeField(db_column='AccessTokenExpiry')),
                ('refresh_token_expiry', models.DateTimeField(db_column='RefreshTokenExpiry')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('is_revoked', models.BooleanField(db_column='IsRevoked', default=False)),
                ('account', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tokens',
            },
        ),
    ]
