# Generated by Django 5.2.7 on 2025-10-04 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_tokens'),
        ('payments', '0002_alter_student_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to='payments.student'),
        ),
    ]
