# Generated by Django 5.2.7 on 2025-10-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='student',
        ),
    ]
