# Generated by Django 5.2.6 on 2025-10-31 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentCode', models.CharField(max_length=32, verbose_name='Mã sinh viên')),
                ('CourseId', models.CharField(max_length=32, verbose_name='Max mon hoc')),
                ('WeightAttendance', models.FloatField(default=0.1)),
                ('WeightMidterm', models.FloatField(default=0.2)),
                ('WeightFinal', models.FloatField(default=0.7)),
                ('Attendance', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm chuyên cần')),
                ('Midterm', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm giữa kỳ')),
                ('Final', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm cuối kỳ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Scores',
                'ordering': ['StudentCode', 'CourseId'],
                'indexes': [models.Index(fields=['StudentCode'], name='Scores_Student_d592d6_idx'), models.Index(fields=['CourseId'], name='Scores_CourseI_ba8183_idx')],
            },
        ),
    ]
