# Generated by Django 5.2.7 on 2025-10-13 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('FacultyID', models.AutoField(primary_key=True, serialize=False)),
                ('FacultyName', models.CharField(max_length=100)),
                ('Office', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('Credit', models.IntegerField()),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.faculty')),
            ],
            options={
                'verbose_name': 'Course',
                'db_table': 'Courses',
            },
        ),
    ]
