# Generated by Django 5.2.7 on 2025-10-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
