# Generated by Django 5.2.7 on 2025-10-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='StudentID', primary_key=True, serialize=False)),
                ('account_id', models.IntegerField(blank=True, db_column='AccountID', null=True)),
                ('full_name', models.CharField(db_column='FullName', max_length=100)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, db_column='BirthDate', null=True)),
                ('email', models.EmailField(db_column='Email', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('major_id', models.IntegerField(blank=True, db_column='MajorID', null=True)),
                ('admission_year', models.IntegerField(blank=True, db_column='AdmissionYear', null=True)),
            ],
            options={
                'db_table': 'Students',
                'ordering': ['id'],
            },
        ),
    ]
