# Generated by Django 5.2.6 on 2025-11-06 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(db_column='StudentID', max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='FullName', max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Nữ'), ('M', 'Nam')], db_column='Gender', max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, db_column='BirthDate', null=True)),
                ('email', models.EmailField(db_column='Email', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('admission_year', models.IntegerField(blank=True, db_column='AdmissionYear', null=True)),
                ('account', models.OneToOneField(blank=True, db_column='AccountID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('major', models.ForeignKey(db_column='MajorID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='majors.major')),
            ],
            options={
                'db_table': 'Students',
                'ordering': ['student_id'],
            },
        ),
    ]
