# Generated by Django 5.2.7 on 2025-10-06 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(db_column='FacultyID', primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(db_column='FacultyName', max_length=100)),
                ('office', models.CharField(db_column='Office', max_length=100)),
                ('phone', models.CharField(db_column='Phone', max_length=15)),
            ],
            options={
                'db_table': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(db_column='ScheduleID', primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(db_column='DayOfWeek', max_length=15)),
                ('start_period', models.IntegerField(db_column='StartPeriod')),
                ('period_count', models.IntegerField(db_column='PeriodCount')),
                ('start_date', models.DateField(db_column='StartDate')),
                ('end_date', models.DateField(db_column='EndDate')),
                ('room', models.CharField(db_column='Room', max_length=100)),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(db_column='SemesterID', primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_column='Year')),
                ('term', models.CharField(db_column='Term', max_length=20)),
                ('credit_fee', models.DecimalField(db_column='CreditFee', decimal_places=2, max_digits=12)),
                ('start_date', models.DateField(db_column='StartDate')),
                ('end_date', models.DateField(db_column='EndDate')),
            ],
            options={
                'db_table': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(db_column='CourseID', primary_key=True, serialize=False)),
                ('course_name', models.CharField(db_column='CourseName', max_length=100)),
                ('credit', models.IntegerField(db_column='Credit')),
                ('faculty', models.ForeignKey(db_column='FacultyID', on_delete=django.db.models.deletion.CASCADE, to='payments.faculty')),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.AutoField(db_column='LecturerID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='FullName', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('phone', models.CharField(db_column='Phone', max_length=15)),
                ('office', models.CharField(db_column='Office', max_length=100)),
                ('account', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(db_column='FacultyID', on_delete=django.db.models.deletion.CASCADE, to='payments.faculty')),
            ],
            options={
                'db_table': 'Lecturers',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(db_column='ClassID', primary_key=True, serialize=False)),
                ('class_name', models.CharField(db_column='ClassName', max_length=100)),
                ('capacity', models.IntegerField(db_column='Capacity')),
                ('course', models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.CASCADE, to='payments.course')),
                ('lecturer', models.ForeignKey(db_column='LecturerID', on_delete=django.db.models.deletion.CASCADE, to='payments.lecturer')),
                ('schedule', models.ForeignKey(db_column='ScheduleID', on_delete=django.db.models.deletion.CASCADE, to='payments.schedule')),
                ('semester', models.ForeignKey(db_column='SemesterID', on_delete=django.db.models.deletion.CASCADE, to='payments.semester')),
            ],
            options={
                'db_table': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('payment_id', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(db_column='PaidAmount', decimal_places=2, max_digits=12)),
                ('status', models.CharField(db_column='Status', max_length=20)),
                ('due_date', models.DateField(db_column='DueDate')),
                ('paid_date', models.DateField(blank=True, db_column='PaidDate', null=True)),
                ('semester', models.ForeignKey(db_column='SemesterID', on_delete=django.db.models.deletion.CASCADE, to='payments.semester')),
                ('student', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'StudentPayments',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_grade', models.DecimalField(blank=True, db_column='MidtermGrade', decimal_places=2, max_digits=4, null=True)),
                ('final_grade', models.DecimalField(blank=True, db_column='FinalGrade', decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(db_column='Status', max_length=20)),
                ('enrollment_date', models.DateField(db_column='EnrollmentDate')),
                ('class_obj', models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.CASCADE, to='payments.class')),
                ('student', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'Enrollments',
                'unique_together': {('student', 'class_obj')},
            },
        ),
        migrations.CreateModel(
            name='MajorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(db_column='IsRequired')),
                ('course', models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.CASCADE, to='payments.course')),
                ('major', models.ForeignKey(db_column='MajorID', on_delete=django.db.models.deletion.CASCADE, to='majors.major')),
            ],
            options={
                'db_table': 'Major_Course',
                'unique_together': {('major', 'course')},
            },
        ),
    ]
