# Generated by Django 5.2.7 on 2025-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(db_column='MajorID', primary_key=True, serialize=False)),
                ('major_name', models.CharField(db_column='MajorName', max_length=100)),
                ('faculty_name', models.CharField(blank=True, db_column='FacultyName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Majors',
            },
        ),
    ]
