# Generated by Django 5.2.6 on 2025-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('Credit', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Course',
                'db_table': 'Courses',
            },
        ),
    ]
